package br.com.irse.verse.core

object BibleConstants {
    val BOOK_ABBREVIATIONS: Map<String, String> = mapOf(
        "gn" to "Gênesis", "genesis" to "Gênesis",
        "ex" to "Êxodo", "exodo" to "Êxodo",
        "lv" to "Levítico", "lev" to "Levítico",
        "nm" to "Números", "num" to "Números",
        "dt" to "Deuteronômio", "deut" to "Deuteronômio",
        "js" to "Josué", "jos" to "Josué",
        "jz" to "Juízes", "jui" to "Juízes",
        "rt" to "Rute", "rut" to "Rute",
        "1 sm" to "1 Samuel", "1sm" to "1 Samuel", "i sm" to "1 Samuel",
        "2 sm" to "2 Samuel", "2sm" to "2 Samuel", "ii sm" to "2 Samuel",
        "1 rs" to "1 Reis", "1rs" to "1 Reis", "i rs" to "1 Reis",
        "2 rs" to "2 Reis", "2rs" to "2 Reis", "ii rs" to "2 Reis",
        "1 cr" to "1 Crônicas", "1cr" to "1 Crônicas", "i cr" to "1 Crônicas",
        "2 cr" to "2 Crônicas", "2cr" to "2 Crônicas", "ii cr" to "2 Crônicas",
        "ed" to "Esdras", "esd" to "Esdras",
        "ne" to "Neemias", "nee" to "Neemias",
        "et" to "Ester", "est" to "Ester",
        "jo" to "Jó", "job" to "Jó",
        "jó" to "Jó",
        "sl" to "Salmos", "sal" to "Salmos",
        "pv" to "Provérbios", "prov" to "Provérbios",
        "ec" to "Eclesiastes", "ecl" to "Eclesiastes",
        "ct" to "Cânticos", "cant" to "Cânticos",
        "is" to "Isaías", "isa" to "Isaías",
        "jr" to "Jeremias", "jer" to "Jeremias",
        "lm" to "Lamentações", "lam" to "Lamentações",
        "ez" to "Ezequiel", "eze" to "Ezequiel",
        "dn" to "Daniel", "dan" to "Daniel",
        "os" to "Oséias", "ose" to "Oséias",
        "jl" to "Joel",
        "am" to "Amós",
        "ob" to "Obadias",
        "jn" to "Jonas", "jon" to "Jonas",
        "mq" to "Miquéias", "miq" to "Miquéias",
        "na" to "Naum",
        "hc" to "Habacuque", "hab" to "Habacuque",
        "sf" to "Sofonias", "sof" to "Sofonias",
        "ag" to "Ageu",
        "zc" to "Zacarias", "zac" to "Zacarias",
        "ml" to "Malaquias", "mal" to "Malaquias",
        "mt" to "Mateus", "mat" to "Mateus",
        "mc" to "Marcos", "mar" to "Marcos",
        "lc" to "Lucas", "luc" to "Lucas",
        "jo" to "João", "joao" to "João",
        "at" to "Atos", "atos" to "Atos",
        "rm" to "Romanos", "rom" to "Romanos",
        "1 co" to "1 Coríntios", "1co" to "1 Coríntios",
        "2 co" to "2 Coríntios", "2co" to "2 Coríntios",
        "gl" to "Gálatas", "gal" to "Gálatas",
        "ef" to "Efésios",
        "efesios" to "Efésios",
        "fp" to "Filipenses", "fil" to "Filipenses",
        "cl" to "Colossenses", "col" to "Colossenses",
        "colossenses" to "Colossenses",
        "1 ts" to "1 Tessalonicenses", "1ts" to "1 Tessalonicenses",
        "2 ts" to "2 Tessalonicenses", "2ts" to "2 Tessalonicenses",
        "1 tm" to "1 Timóteo", "1tm" to "1 Timóteo",
        "2 tm" to "2 Timóteo", "2tm" to "2 Timóteo",
        "tt" to "Tito",
        "fm" to "Filemom",
        "hb" to "Hebreus", "heb" to "Hebreus",
        "tg" to "Tiago",
        "1 pe" to "1 Pedro", "1pe" to "1 Pedro",
        "2 pe" to "2 Pedro", "2pe" to "2 Pedro",
        "1 jo" to "1 João", "1jo" to "1 João",
        "2 jo" to "2 João", "2jo" to "2 João",
        "3 jo" to "3 João", "3jo" to "3 João",
        "jd" to "Judas",
        "ap" to "Apocalipse", "apoc" to "Apocalipse"
    )
}
