name: bereiaverse
title: Bereia Versículos
version: '1.2.0'
summary: Seu Assistente Bíblico Inteligente.
description: |
  Copie uma referência, veja o versículo na hora. Leve, rápido e com notas integradas para seus estudos.
  Chega de alternar entre abas ou abrir programas pesados para consultar versículos. O Bereia Versículos traz a Bíblia até você: basta copiar a referência e o texto aparece de forma rápida e elegante.
  Seja preparando um sermão, estudando para a escola dominical ou pesquisando para trabalhos acadêmicos, o Bereia oferece acesso imediato às Escrituras, além de um sistema de notas integrado para registrar cada revelação ou insight.

website: https://irse.com.br
contact: https://github.com/Instituto-Reformado-Santo-Evangelho/bereia-verse/issues
source-code: https://github.com/Instituto-Reformado-Santo-Evangelho/bereia-verse

grade: stable
confinement: strict
base: core24

# O ícone principal do snap (arquivo local usado durante o build)
icon: app/composeApp/src/desktopMain/resources/bereiaverse.png

platforms:
  amd64:

apps:
  bereiaverse:
    command: bin/bereiaverse
    extensions: [gnome]
    plugs:
      - x11
      - wayland
      - opengl
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - gsettings
    environment:
      JAVA_TOOL_OPTIONS: "-Dorg.jetbrains.skiko.renderApi=OPENGL -Dskiko.linux.display.server=Wayland -Djava.awt.headless=false"
      PATH: $SNAP/usr/lib/jvm/java-21-openjdk-amd64/bin:$PATH

parts:
  bereia-verse:
    plugin: nil
    source: .
    build-environment:
      - GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      - GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    build-packages:
      - openjdk-21-jdk
      - libasound2-dev
      - libpng-dev
      - libgl1-mesa-dev
      - libx11-dev
      - zlib1g-dev
    stage-packages:
      - libasound2t64
      - libgl1
      - wl-clipboard
      - xclip
    override-build: |
      export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      
      cd app
      ./gradlew :composeApp:createDistributable --no-daemon
      
      # O caminho correto do binário gerado pelo Compose
      DIST_PATH="composeApp/build/compose/binaries/main/app/bereiaverse"
      
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      
      # Copia apenas o necessário da distribuição gerada
      cp -r $DIST_PATH/bin/* $SNAPCRAFT_PART_INSTALL/bin/
      cp -r $DIST_PATH/lib/* $SNAPCRAFT_PART_INSTALL/lib/
      
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/bereiaverse

      # Ícone
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      cp composeApp/src/desktopMain/resources/bereiaverse.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/bereiaverse.png
