name: Build Extensions

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, Tag ou SHA do bereia-verse para compilar'
        required: false
        default: ''

jobs:
  build-and-release:
    name: Build and Release Extensions
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout Ref (Tag or Master)
      shell: bash
      run: |
        REF="${{ github.event.inputs.ref || github.ref_name }}"
        echo "Checking out $REF..."
        git checkout $REF || git checkout master

    - name: Package Chrome Extension
      run: |
        cd ext-chrome && zip -r ../ext-bereia-verse.zip .

    - name: Package WordPress Plugin
      run: |
        cd wp-plugin && zip -r ../wp-bereia-verse.zip .

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: |
          ext-bereia-verse.zip
          wp-bereia-verse.zip
