name: Build macOS App

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, Tag ou SHA do bereia-verse para compilar'
        required: false
        default: ''

jobs:
  build-mac:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout Ref (Tag or Master)
      shell: bash
      run: |
        REF="${{ github.event.inputs.ref || github.ref_name }}"
        echo "Checking out $REF..."
        git checkout $REF || git checkout master

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x app/gradlew

    - name: Create temporary client_secrets.json
      env:
        GOOGLE_CLIENT_SECRETS_JSON: ${{ secrets.GOOGLE_CLIENT_SECRETS_JSON }}
      run: |
        if [ -n "$GOOGLE_CLIENT_SECRETS_JSON" ]; then
          echo "Creating client_secrets.json from secret..."
          mkdir -p app/composeApp/src/commonMain/resources
          echo "$GOOGLE_CLIENT_SECRETS_JSON" > app/composeApp/src/commonMain/resources/client_secrets.json
        else
          echo "Secret not found. Skipping client_secrets.json creation."
        fi

    - name: Build macOS DMG
      run: ./app/gradlew -p ./app packageDmg --no-configuration-cache

    - name: Remove temporary client_secrets.json
      if: always() && steps.create_secrets.conclusion == 'success'
      run: rm app/composeApp/src/commonMain/resources/client_secrets.json


    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: app/composeApp/build/compose/binaries/main/dmg/*.dmg
