name: Build Snap

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, Tag ou SHA do bereia-verse para compilar'
        required: false
        default: ''
  push:
    tags:
      - 'v*'

jobs:
  build-snap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Create temporary client_secrets.json
        env:
          GOOGLE_CLIENT_SECRETS_JSON: ${{ secrets.GOOGLE_CLIENT_SECRETS_JSON }}
        run: |
          if [ -n "$GOOGLE_CLIENT_SECRETS_JSON" ]; then
            echo "Creating client_secrets.json from secret..."
            mkdir -p app/composeApp/src/commonMain/resources
            echo "$GOOGLE_CLIENT_SECRETS_JSON" > app/composeApp/src/commonMain/resources/client_secrets.json
          else
            echo "Secret not found. Skipping client_secrets.json creation."
          fi

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: build
        with:
          path: linux/snap

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep 'packageVersion =' app/composeApp/build.gradle.kts | cut -d '"' -f 2)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Remove temporary client_secrets.json
        if: always()
        run: |
          if [ -f "app/composeApp/src/commonMain/resources/client_secrets.json" ]; then
            rm app/composeApp/src/commonMain/resources/client_secrets.json
          fi

      - name: Publish to Snap Store
        uses: snapcore/action-publish@v1
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', env.APP_VERSION) }}
          files: |
            ${{ steps.build.outputs.snap }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
